# Lang
language: en

# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss:

# Content
fancybox: true


# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: darrenFantasy
description: 说出来会被嘲笑的梦想，才有实现的价值。
links:
  Blog: /archives
  GitHub: https://github.com/darrenfantasy
  Email: mailto:yuanda.wang1993@gmail.com
  About: /about

# Info
archive_footer_content: 温度不迷茫，方向不倔强。
post_footer_content: stay hungry , stay foolish .

duoshuo_shortname: darrenfantasy